export const DRUG_REMINDER_NOTIFICATION_ID = 'DRUG_REMINDER_NOTIFICATION_ID';
export const DRUG_REMINDER_NOTIFICATION_CHANNEL_ID = 'DRUG_REMINDER_NOTIFICATION_CHANNEL_ID';
export const DRUG_REMINDER_NOTIFICATION_CHANNEL_NAME = 'Drug Reminders';
export const DRUG_REMINDER_NOTIFICATION_CHANNEL_DESCRIPTION = 'Notifications for taking drugs on time';